### ISSUE TITLE
Reset/Forgot password page (<- write support page explaining why this is missing)

### ISSUE THREAD

**Issue by lucasjose501** [Blobbackup/Blobbackup#99] opened 2022-03-09 17:55 UTC
The user can not reset the password if he doesn't remember it.

**Comment by bimbashrestha** [comment] 2022-03-09 18:15
Hey @lucasjose501! Thanks for posting. This is by design.

Blobbackup works like a password manager (like Bitwarden, 1Password). The password created during registration is what's used to encrypt all the user's computer data. It's designed this way to allow for better privacy. Password Managers (at least the good ones) don't let you reset your password either for this reason. I should write up a support page to explain this sometime. Here is some helpful info on this from 1Password's support site.


>For your security, your account password is:
>
>never transmitted over the internet
>never logged locally
>never known to us at 1Password
>only known to you
>the only way to decrypt your data
>
>This makes sure that your data is safe from intruders, but it also means that no one can reset your password. However, you might be able to recover access to your data.

[source] https://support.1password.com/forgot-account-password/

**Comment by lucasjose501** [comment] 2022-03-09 18:58
Oh, I see. I just skipped the warning text in the registration page (Sorry). My mistake.

**Comment by bimbashrestha** [comment] 2022-03-14 02:09
Added an article in 9d8057e09e5aa1eaa08dfe2a138a68842e4d8355. Closing

**Closed by bimbashrestha** 2022-03-14 02:09 UTC
Labels: documentation
