### ISSUE TITLE
i loss my password...

### ISSUE THREAD

**Issue by Jamlee** [BlobBackup/BlobBackup#48] opened 2021-04-24 04:04 UTC
how to get back my password of backup.

**Comment by bimbashrestha** [comment] 2021-04-25 00:52
Hi @Jamlee, I have some bad news for you. We are most likely not going to be able to recover your password. Your password is never stored anywhere in the backup destination (by design) and as the docs (https://blobbackup.readthedocs.io/en/latest/backup/#local-directory) indicate, losing your password means losing the ability to decrypt your data. This behavior makes it impossible for the user's privacy to be compromised without the user's password. But unfortunately, it has the downside of not being able to "get back" your password if your forget it. 

That said, we might still be able to get your password back if we're lucky. Are you running BlobBackup on a new computer to restore files or on the original computer? A quick way to check is by seeing if you can still create backups by hitting the "run" button on the GUI (if you can, it means you're using it on your original computer).

Once you report back, we'll see if we can recover the password that is stored in encrypted form on your system's keyring. Also what operating system are you using?

**Comment by Jamlee** [comment] 2021-04-25 01:42
i have dredged up my password in the same room setting password. thanks. ^-^.

lossing password is a probelm, i seldom entry my password.  what do you think about that encrypt password use `private key`. 
store encrypted password and data together. so i could decrypted data by `password` or  `private key`

**Comment by bimbashrestha** [comment] 2021-04-30 13:33
@Jamlee Glad you found your password. 

So your password is automatically stored in your system's keyring (keychaing on osx, credential manager on windows, keyring on linux). So if you lose it again and you haven't also lost your computer, you can find your password through there with a little hassle but it's doable.

You might also consider using a password manager of some kind. They will solve this problem of having to remember your password:)

About your idea, we'll have to see how many more people will find something like that useful. I'll make a note of it now in case it ever comes up again in the future. I'm going to close this issue for now but feel free to continue leaving comments.

**Closed by bimbashrestha** 2021-04-30 13:33 UTC
Labels: question
